services:
  - type: web
    name: student-dashboard-server
    env: node
    region: oregon
    plan: free
    rootDir: server
    buildCommand: apt-get install -y tesseract-ocr poppler-utils libgl1 && pip install pdf2image pytesseract opencv-python-headless pdfplumber Pillow && npm install
    startCommand: npm start
    envVarGroups: []
